# [Day 4](https://adventofcode.com/2023/day/4)

In [1]:
import numpy as np
import pandas as pd
from collections import defaultdict

In [2]:
# Read inputs
isTest = not True
fileName = "test" if isTest else "input"
with open(fileName) as f:
    input = [l.strip("\n") for l in f.readlines()]

print(len(input))

192

In [3]:
def process_line(line: str):
    def breakLine(line: str) -> (str, str, np.ndarray, np.ndarray):
        [game_id_str, values] = line.split(":")
        [winning, numbers] = values.split("|")

        return (
            game_id_str,
            game_id_str.split(" ")[-1],
            np.array(np.char.split(winning.strip(" ")).tolist()),
            np.array(np.char.split(numbers.strip(" ")).tolist()),
        )

    get_points = lambda n: 2 ** (n - 1) if n > 0 else n
    game, id, winning, numbers = breakLine(line)
    matches = np.isin(numbers, winning).sum()
    return {
        "game": game,
        "id": id,
        "winning": winning,
        "numbers": numbers,
        "matches": matches,
        "points": get_points(matches),
    }


process_lines = np.vectorize(process_line)


processed_data = list(map(process_line, input))
df = pd.DataFrame(processed_data)
df

,game,id,winning,numbers,matches,points
0,Card 1,1,"[77, 45, 9, 81, 96, 5, 91, 3, 66, 76]","[7, 56, 66, 49, 96, 58, 54, 34, 37, 5, 14, 85,...",10,512
1,Card 2,2,"[41, 49, 12, 46, 39, 9, 72, 78, 24, 76]","[3, 28, 60, 82, 2, 26, 67, 75, 37, 72, 64, 46,...",3,4
2,Card 3,3,"[26, 93, 49, 51, 21, 50, 33, 69, 73, 28]","[64, 18, 76, 80, 65, 89, 78, 38, 37, 75, 14, 9...",1,1
3,Card 4,4,"[75, 85, 30, 17, 82, 27, 51, 28, 94, 90]","[2, 6, 1, 83, 65, 21, 30, 70, 22, 91, 11, 26, ...",1,1
4,Card 5,5,"[95, 59, 90, 56, 69, 67, 12, 57, 6, 68]","[61, 52, 76, 69, 67, 40, 31, 56, 55, 90, 12, 6...",10,512
...,...,...,...,...,...,...
187,Card 188,188,"[84, 96, 45, 41, 89, 7, 4, 78, 15, 67]","[50, 81, 20, 90, 83, 39, 37, 23, 95, 69, 10, 2...",1,1
188,Card 189,189,"[17, 79, 92, 4, 56, 68, 1, 91, 33, 82]","[5, 84, 58, 42, 73, 9, 86, 59, 48, 44, 52, 55,...",1,1
189,Card 190,190,"[87, 29, 43, 80, 97, 27, 41, 95, 23, 25]","[21, 84, 53, 11, 41, 50, 62, 15, 18, 26, 90, 7...",1,1
190,Card 191,191,"[8, 40, 10, 80, 85, 87, 41, 23, 15, 37]","[58, 27, 21, 41, 62, 1, 71, 43, 18, 26, 38, 4,...",1,1
191,Card 192,192,"[5, 89, 88, 49, 70, 26, 73, 3, 56, 64]","[38, 29, 37, 69, 59, 14, 22, 78, 66, 9, 75, 86...",0,0

## Part 2

In [4]:
copies = defaultdict(int)
for ix, matches in enumerate(df["matches"]):
    copies[ix] += 1
    for i in range(matches):
        key = ix + 1 + i
        copies[key] += copies[ix]

df["copies"] = pd.Series(copies)
df

,game,id,winning,numbers,matches,points,copies
0,Card 1,1,"[77, 45, 9, 81, 96, 5, 91, 3, 66, 76]","[7, 56, 66, 49, 96, 58, 54, 34, 37, 5, 14, 85,...",10,512,1
1,Card 2,2,"[41, 49, 12, 46, 39, 9, 72, 78, 24, 76]","[3, 28, 60, 82, 2, 26, 67, 75, 37, 72, 64, 46,...",3,4,2
2,Card 3,3,"[26, 93, 49, 51, 21, 50, 33, 69, 73, 28]","[64, 18, 76, 80, 65, 89, 78, 38, 37, 75, 14, 9...",1,1,4
3,Card 4,4,"[75, 85, 30, 17, 82, 27, 51, 28, 94, 90]","[2, 6, 1, 83, 65, 21, 30, 70, 22, 91, 11, 26, ...",1,1,8
4,Card 5,5,"[95, 59, 90, 56, 69, 67, 12, 57, 6, 68]","[61, 52, 76, 69, 67, 40, 31, 56, 55, 90, 12, 6...",10,512,12
...,...,...,...,...,...,...,...
187,Card 188,188,"[84, 96, 45, 41, 89, 7, 4, 78, 15, 67]","[50, 81, 20, 90, 83, 39, 37, 23, 95, 69, 10, 2...",1,1,5364
188,Card 189,189,"[17, 79, 92, 4, 56, 68, 1, 91, 33, 82]","[5, 84, 58, 42, 73, 9, 86, 59, 48, 44, 52, 55,...",1,1,10720
189,Card 190,190,"[87, 29, 43, 80, 97, 27, 41, 95, 23, 25]","[21, 84, 53, 11, 41, 50, 62, 15, 18, 26, 90, 7...",1,1,13344
190,Card 191,191,"[8, 40, 10, 80, 85, 87, 41, 23, 15, 37]","[58, 27, 21, 41, 62, 1, 71, 43, 18, 26, 38, 4,...",1,1,14784
191,Card 192,192,"[5, 89, 88, 49, 70, 26, 73, 3, 56, 64]","[38, 29, 37, 69, 59, 14, 22, 78, 66, 9, 75, 86...",0,0,16128

In [5]:
df["copies"].sum()

23806951