# [Day 5](https://adventofcode.com/2023/day/5)

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read inputs
isTest = not True
fileName = "test" if isTest else "input"
with open(fileName) as f:
    input = [l.strip("\n") for l in f.readlines()]

print(len(input))

193

In [3]:
def process_sections(lines: [str]):
    def prc_range(lines: [str]):
        def get_range(line: str):
            [des, src, offset] = np.array(line.split()).astype(int)
            return src, des, offset
            # return r, lambda n: n + offset if n in r else n

        ranges = [get_range(l) for l in lines]

        def mapper(src: int):
            for src_org, destination, offset in ranges:
                if src_org <= src < (src_org + offset) :
                    return destination + src - src_org
            return src

        return mapper

    seeds = np.array(lines[0].split(":")[1].split(), dtype=int)
    sts, stf, ftw, wtl, ltt, tth, htl = tuple(
        np.argwhere(np.char.find(input, "map") > 0).T[0]
    )
    return {
        "seeds": seeds.tolist(),
        "seed-to-soil": prc_range(input[sts + 1 : stf - 1]),
        "soil-to-fertilizer": prc_range(input[stf + 1 : ftw - 1]),
        "fertilizer-to-water": prc_range(input[ftw + 1 : wtl - 1]),
        "water-to-light": prc_range(input[wtl + 1 : ltt - 1]),
        "light-to-temperature": prc_range(input[ltt + 1 : tth - 1]),
        "temperature-to-humidity": prc_range(input[tth + 1 : htl - 1]),
        "humidity-to-location": prc_range(input[htl + 1 :]),
    }


map_table = process_sections(input)
map_table.keys()

dict_keys(['seeds', 'seed-to-soil', 'soil-to-fertilizer', 'fertilizer-to-water', 'water-to-light', 'light-to-temperature', 'temperature-to-humidity', 'humidity-to-location'])

In [4]:
val = 10
if 8 <= val < 8+2:
  print('yay')

In [5]:
[{i: map_table['seed-to-soil'](i)} for i in [0, 1, 48, 49, 50, 51, 96, 97, 98, 99]]

[{0: 0},
 {1: 1},
 {48: 48},
 {49: 49},
 {50: 50},
 {51: 51},
 {96: 96},
 {97: 97},
 {98: 98},
 {99: 99}]

In [6]:
seeds = map_table['seeds']
for seed in seeds:
  soil = map_table['seed-to-soil'](seed) 
  print(seed,soil)

2276375722 2783521882
160148132 160148132
3424292843 3682952589
82110297 82110297
1692203766 2310835152
342813967 342813967
3289792522 3548452268
103516087 103516087
2590548294 2376935866
590357761 590357761
1365412380 1365412380
80084180 80084180
3574751516 1996337070
584781136 584781136
4207087048 4028360926
36194356 36194356
1515742281 3738464147
174009980 174009980
6434225 6434225
291842774 291842774

In [7]:
map_table

{'seeds': [2276375722,
  160148132,
  3424292843,
  82110297,
  1692203766,
  342813967,
  3289792522,
  103516087,
  2590548294,
  590357761,
  1365412380,
  80084180,
  3574751516,
  584781136,
  4207087048,
  36194356,
  1515742281,
  174009980,
  6434225,
  291842774],
 'seed-to-soil': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>,
 'soil-to-fertilizer': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>,
 'fertilizer-to-water': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>,
 'water-to-light': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>,
 'light-to-temperature': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>,
 'temperature-to-humidity': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>,
 'humidity-to-location': <function __main__.process_sections.<locals>.prc_range.<locals>.mapper(src: int)>}

In [8]:
seeds = np.array(map_table['seeds']).astype(np.uint64)
get_soil = np.vectorize(map_table["seed-to-soil"])
get_soil(seed)

array(291842774)

In [9]:
def seed_info(seed: int, mapper: dict):
    def get_destination(src, key: str):
        return mapper[key](src)

    soil = get_destination(seed, "seed-to-soil")
    fertilizer = get_destination(soil, "soil-to-fertilizer")
    water = get_destination(fertilizer, "fertilizer-to-water")
    light = get_destination(water, "water-to-light")
    temperature = get_destination(light, "light-to-temperature")
    humidity = get_destination(temperature, "temperature-to-humidity")
    location = get_destination(humidity, "humidity-to-location")
    return {
        "seed": seed,
        "soil": soil,
        "fertilizer": fertilizer,
        "water": water,
        "light": light,
        "temperature": temperature,
        "humidity": humidity,
        "location": location,
    }


df = pd.DataFrame(list(map(lambda s: seed_info(s, map_table), map_table['seeds'])))
df

,seed,soil,fertilizer,water,light,temperature,humidity,location
0,2276375722,2783521882,1668595564,1474182774,508540401,508540401,3797527809,4028400537
1,160148132,160148132,160148132,738154308,3290382145,857953299,3910823632,4141696360
2,3424292843,3682952589,364049742,1164339880,994534103,532218727,3821206135,4052078863
3,82110297,82110297,82110297,1981023012,1933243843,1735569008,1919212440,2038059236
4,1692203766,2310835152,1195908834,1560424790,1512645621,4159012109,666242823,1366539071
5,342813967,342813967,3395763873,2935936081,555666541,3708485690,4292581585,4292581585
6,3289792522,3548452268,2094256020,425620568,2977848405,3487974480,334167070,1100109810
7,103516087,103516087,103516087,2002428802,1954649633,1756974798,1940618230,2059465026
8,2590548294,2376935866,1262009548,1626525504,1578746335,1381071500,1116761294,2281590465
9,590357761,590357761,3643307667,2619324917,2571545748,3239922958,4056521420,2758382622
10,1365412380,1365412380,2773258784,3254182858,3729202254,2672347957,1280135127,2444964298
11,80084180,80084180,80084180,1978996895,1931217726,1733542891,1917186323,2036033119
12,3574751516,1996337070,4046379981,3958192861,454881471,454881471,3743868879,3974741607
13,584781136,584781136,3637731042,2613748292,2565969123,3234346333,4050944795,2752805997
14,4207087048,4028360926,709458079,991779062,88235691,93788767,93788767,859731507
15,36194356,36194356,36194356,1935107071,1887327902,1689653067,1873296499,1992143295
16,1515742281,3738464147,419561300,1219851438,1050045661,587730285,3508261333,484023871
17,174009980,174009980,174009980,752016156,3304243993,871815147,3924685480,4155558208
18,6434225,6434225,6434225,1905346940,1857567771,1659892936,2177592517,697471736
19,291842774,291842774,3344792680,2864291750,3883317853,2826463556,2508216881,3318428117

In [10]:
df['location'].min()

484023871

In [11]:
# s1, s2 = map_table['seeds'][0:2]
# l = list(range(s1, s1+ s2))
# pd.DataFrame(list(map(lambda s: seed_info(s, map_table), l)))